#!/usr/bin/env bash
set -e
if [[ -z "${PORT}" ]]; then
  echo "fatal: \$PORT not set" >&2
  exit 1
fi
sed -i.orig -e "s/\$PORT/${PORT}/g" .nginx/conf/nginx.conf
exec .nginx/sbin/nginx -c $PWD/.nginx/conf/nginx.conf -g "worker_processes $(nproc);"
